const sampleProducts = [
    
    {
        id: 2,
        name: "Caja de Pollo",
        description: "caja de 40 lb de muslo y contramuslo 4 paquetes de 10 lb",
        category: "alimentos",
        image: "images/pollocaja.png",
        reciente: 0,
      },
      {
        id: 3,
        name: "Paquete de pollo 10 lb",
        description: "paquete de 10 lb de muslo y contra muslo",
        category: "alimentos",
        image: "images/pollopqte.png",
      },
      {
        id: 4,
        name: "Lomo de cerdo deshuesado",
        description: "Lomo de cerdo Importado sellado en bolsa de 4 lb",
        category: "alimentos",
        image: "images/lomo.png",
      },
      {
        id: 8,
        name: "Jamon vicky",
        description: "Porción de 3 lb sellado al vacio",
        category: "alimentos",
        image: "images/vicky.png",
      },
      {
        id: 9,
        name: "Lomo ahumado",
        description: "porcionado y sellado en 2 lb",
        category: "alimentos",
        image: "images/ahumado.png",
        descuento: 10,
      },
      {
        id: 11,
        name: "Pechuga de pollo",
        description: "Paquete de 2 kg",
        category: "alimentos",
        image: "images/pechuga.png",
      },
      {
        id: 12,
        name: "Jamón Embuchado",
        description: "Porción sellada de 3 Lb",
        category: "alimentos",
        image: "images/embuchado.png",
      },
      {
        id: 13,
        name: "Picadillo de pollo",
        description: "unidad de 400 gr",
        category: "alimentos",
        image: "images/picadillo.png",
      },
      {
        id: 14,
        name: "Salchichas",
        description: "paquete de 12 unidades",
        category: "alimentos",
        image: "images/perritos.png",
      },
      {
        id: 16,
        name: "Atún",
        description: "Lata de 1 Kg en aceite",
        category: "alimentos",
        image: "images/atun.png",
      },
      {
        id: 101,
        name: "Hamburguesas Mixtas",
        description: "Bolsa de 5 Hamburguesas de 90 gr cada una",
        category: "alimentos",
        image: "images/hamburguesas.png",
      },
      // Alimentos (Líquidos)
      {
        id: 17,
        name: "Cerveza Cristal",
        description: "Caja de 24 uds",
        category: "alimentos",
        image: "images/cristal.png",
      },
      {
        id: 18,
        name: "Cerveza Bucanero",
        description: "Caja de 24 uds",
        category: "alimentos",
        image: "images/bucanero.png",
      },
      {
        id: 19,
        name: "Cerveza Economica",
        description: "Caja de 24 uds",
        category: "alimentos",
        image: "images/timber.png",
      },
      {
        id: 20,
        name: "Vino Acantus",
        description: "Botella de vino rosado, tinto o Blanco",
        category: "alimentos",
        image: "images/acantus.png",
      },
      {
        id: 21,
        name: "Vino Espumoso",
        description: "botella de vino espumoso Varons d Valls 750 ml",
        category: "alimentos",
        image: "images/espumoso.png",
      },
      {
        id: 22,
        name: "Ron Habana Club",
        description: "Añejo 3 años 750 ml",
        category: "alimentos",
        image: "images/3años.png",
      },
      {
        id: 24,
        name: "Jugo",
        description: "Caja de 24 uds de 200 ml",
        category: "alimentos",
        image: "images/200ml.png",
      },
      {
        id: 25,
        name: "Jugo",
        description: "Jugo La estancia Sabor Naranja 1 L",
        category: "alimentos",
        image: "images/naranja.png",
      },
      {
        id: 26,
        name: "Jugo",
        description: "Blister de 6 uds 330 ml Multifrutas de lata",
        category: "alimentos",
        image: "images/multifrutas.png",
      },
      {
        id: 27,
        name: "Malta Morena",
        description: "Caja de 24 uds",
        category: "alimentos",
        image: "images/morena.png",
      },
      {
        id: 28,
        name: "Refresco",
        description: "Lata 330 ml",
        category: "alimentos",
        image: "images/refrescolata.png",
      },
      {
        id: 202,
        name: "Refresco Zuko",
        description: "Caja de 8 sobres",
        category: "alimentos",
        image: "images/zuko.png",
        reciente: 1,
      },
      {
        id: 30,
        name: "Café",
        description: "Paquete de 250 gr",
        category: "alimentos",
        image: "images/aroma.png",
      },
      // Alimentos (Otros)
      {
        id: 31,
        name: "pasta de tomate Sabrosísimo",
        description: "Pasta doble concentrado 800 gr",
        category: "alimentos",
        image: "images/800gr.png",
      },
      {
        id: 35,
        name: "Spaguetis",
        description: "Bolsa de 500 gr",
        category: "alimentos",
        image: "images/spaguetis.png",
      },
      {
        id: 36,
        name: "Codito",
        description: "Bolsa de 500 gr",
        category: "alimentos",
        image: "images/codito.png",
      },
      {
        id: 37,
        name: "Azucar Blanca",
        description: "bolsa de 1 kg",
        category: "alimentos",
        image: "images/azucar1kg.png",
      },
      {
        id: 38,
        name: "Frijol Negro",
        description: "bolsa de 5 Lb",
        category: "alimentos",
        image: "images/frijol5lb.png",
      },
      {
        id: 39,
        name: "Frijol Negro",
        description: "bolsa de 1 kg",
        category: "alimentos",
        image: "images/frijol1kg.png",
      },
      {
        id: 40,
        name: "Frijol Colorado",
        description: "bolsa de 5 Lb",
        category: "alimentos",
        image: "images/colorados5lb.png",
      },
      {
        id: 41,
        name: "Sal Iodada",
        description: "bolsa de 1 Lb",
        category: "alimentos",
        image: "images/sal.png",
      },
      {
        id: 42,
        name: "Arroz Brasileño",
        description: "bolsa de 1 kg",
        category: "alimentos",
        image: "images/arroz1kg.png",
      },
      {
        id: 43,
        name: "Fideos",
        description: "bolsa de 500 gr",
        category: "alimentos",
        image: "images/fideos.png",
      },
     
      {
        id: 45,
        name: "Cartón de huevos",
        description: "30 uds frescos 100 % orgánicos",
        category: "alimentos",
        image: "images/huevo.png",
      },
      {
        id: 201,
        name: "Gelatina",
        description: "Bolsa de gelatina 75 gr",
        category: "alimentos",
        image: "images/gelatina.png",
        reciente: 1,
      },
      // Alimentos (Lácteos)
      {
        id: 100,
        name: "Leche en Polvo",
        description: "Bolsa de 1 kg",
        category: "alimentos",
        image: "images/lechepolvo.png",
      },
      {
        id: 44,
        name: "Helado",
        description: "Caja de 4L",
        category: "alimentos",
        image: "images/helado.png",
        descuento: 10,
      },
      {
        id: 46,
        name: "Leche Condensada",
        description: "Lata con abre fácil",
        category: "alimentos",
        image: "images/condensada.png",
      },
      // Alimentos (Del Agro)
      {
        id: 47,
        name: "Ajo",
        description: "Bolsa de 10 cabezas",
        category: "alimentos",
        image: "images/ajo.png",
      },
      {
        id: 48,
        name: "Malanga",
        description: "bolsa de 5 lb",
        category: "alimentos",
        image: "images/malanga.png",
      },
      {
        id: 49,
        name: "cebolla",
        description: "bolsa de 2.5 lb aproximadamente",
        category: "alimentos",
        image: "images/cebolla.png",
      },
      {
        id: 50,
        name: "Papas frescas",
        description: "Bolsa de 5 lb frescas",
        category: "alimentos",
        image: "images/papas.png",
      },
      // Aseo
      {
        id: 53,
        name: "Frazada de limpiar suelo",
        description: "2 unidad",
        category: "aseo",
        image: "images/frazada.png",
      },
      {
        id: 54,
        name: "Detergente para ropa",
        description: "Pomo de 1 L",
        category: "aseo",
        image: "images/4en1.png",
      },
      {
        id: 55,
        name: "Detergente polvo Multiuso",
        description: "bolsa de 500 gr",
        category: "aseo",
        image: "images/detergente.png",
      },
      {
        id: 56,
        name: "Jabon De Olor",
        description: "por unidades",
        category: "aseo",
        image: "images/jabon.png",
      },
      {
        id: 57,
        name: "Papel Higienico",
        description: "bolsa con 4 unidad sellada",
        category: "aseo",
        image: "images/papel.png",
      },
      {
        id: 58,
        name: "Perlas de olor para ropa",
        description: "frasco de 200 gr",
        category: "aseo",
        image: "images/perlas.png",
      },
      {
        id: 59,
        name: "Suavizante para ropa",
        description: "Pomo de 1 lt",
        category: "aseo",
        image: "images/suavizante.png",
      },
      {
        id: 60,
        name: "Toallitas humedas multiuso premiun",
        description: "Paquete de 120 udst",
        category: "aseo",
        image: "images/toallas.png",
      },
      {
        id: 61,
        name: "Pastillas de inodoro",
        description: "4 uds",
        category: "aseo",
        image: "images/pastillas.png",
      },
      // Electrodomésticos
      {
        id: 62,
        name: "Ventilador de pedestal",
        description: "Ventilador tipo ciclón Milexus",
        category: "electrodomesticos",
        image: "images/ventilador.png",
      },
      {
        id: 63,
        name: "Split milexus",
        description: "Milexus 1200 btu",
        category: "electrodomesticos",
        image: "images/split.png",
      },
      {
        id: 64,
        name: "Frezeer",
        description: "Milexus 5pies",
        category: "electrodomesticos",
        image: "images/nevera.png",
      },
      {
        id: 65,
        name: "Tv de 32",
        description: "Tv inteligente 32 pulgadas",
        category: "electrodomesticos",
        image: "images/32.png",
      },
      {
        id: 66,
        name: "Tv de 55",
        description: "Tv inteligente Milexus 55 pulgadas",
        category: "electrodomesticos",
        image: "images/55.png",
      },
      {
        id: 67,
        name: "Batidora Milexus",
        description: "Batidora 2 en 1 (+ moledor de sazones)",
        category: "electrodomesticos",
        image: "images/batidora.png",
      },
      {
        id: 68,
        name: "Cefetera Milexus",
        description: "Cafetera Electrica de 6 tazas",
        category: "electrodomesticos",
        image: "images/cafetera.png",
      },
      // Alimentos (Del Confi)
      {
        id: 69,
        name: "Choco Biscuit",
        description: "18 gr",
        category: "alimentos",
        image: "images/chocobiscuit.png",
      },
      {
        id: 70,
        name: "Bolita de chocolate",
        description: "bolsa de 500 gr",
        category: "alimentos",
        image: "images/bolitas.png",
      },
      {
        id: 71,
        name: "Best Chocolate",
        description: "Pomo de conitos 595 gr",
        category: "alimentos",
        image: "images/conito.png",
      },
      {
        id: 72,
        name: "Galletas kidi vai vai",
        description: "Paquete de 12 uds",
        category: "alimentos",
        image: "images/kidi.png",
      },
      {
        id: 73,
        name: "Galletas Soda",
        description: "Paquete de 8 uds",
        category: "alimentos",
        image: "images/soda.png",
      },
];
